/**
 * Lightweight product catalogue for CLIENT components (filters, inquiry select, cards).
 * Generated by scripts/extract-products.py (catalog.generated.json). Full product copy lives in products.ts
 * and is only used by server-rendered pages, so it never ships in client JavaScript.
 */
import lite from "./catalog.generated.json";

export type CategoryId = "ip-camera" | "nvr" | "hd-analog-camera" | "dvr" | "software" | "accessory";

export interface CatalogItem {
  slug: string;
  model: string;
  title: string;
  subtitle: string | null;
  tier: string | null;
  category: CategoryId;
  series: string;
  form: string | null;
  environment: string | null;
  image: string;
}

const SOFTWARE_ITEM: CatalogItem = {
  slug: "nvr-cs-vms",
  model: "NVR C/S",
  title: "Video Management Software",
  subtitle: "Video Management Software",
  tier: "Software",
  category: "software",
  series: "VMS",
  form: "VMS",
  environment: null,
  image: "/images/site/vms-screen.webp",
};

export const CATALOG: CatalogItem[] = [...(lite as CatalogItem[]), SOFTWARE_ITEM];

export const CATEGORY_ORDER: CategoryId[] = ["ip-camera", "nvr", "hd-analog-camera", "dvr", "software", "accessory"];

export const FEATURED_SLUGS = ["vnn64lu4ar", "vnv15lu4ar", "vnp36d5var", "vnn32f7vyr", "vnv201tfar", "vr16s", "vd16t", "vtn64184er"] as const;

export function getItem(slug: string): CatalogItem | undefined {
  return CATALOG.find((p) => p.slug === slug);
}
export function productsIn(category: CategoryId): CatalogItem[] {
  return CATALOG.filter((p) => p.category === category);
}
export function seriesOf(category: CategoryId): string[] {
  return Array.from(new Set(productsIn(category).map((p) => p.series)));
}
export function productLine(p: Pick<CatalogItem, "subtitle" | "title">): string {
  return p.subtitle ?? p.title;
}
export function featured(): CatalogItem[] {
  return FEATURED_SLUGS.map((s) => getItem(s)).filter((p): p is CatalogItem => Boolean(p));
}
